def training_cloud_init(job_name: str, run_id: str) -> str:
    """
    VBox-safe demo payload: emits logs to the Nova console via cloud-init.
    No SSH / no floating IP required.
    """
    tpl = """#cloud-config
runcmd:
  - echo "[NOVA-MLOPS] job=__JOB_NAME__ run_id=__RUN_ID__ step=setup"
  - sleep 2
  - echo "[NOVA-MLOPS] job=__JOB_NAME__ run_id=__RUN_ID__ step=train epoch=1 loss=0.91"
  - sleep 2
  - echo "[NOVA-MLOPS] job=__JOB_NAME__ run_id=__RUN_ID__ step=train epoch=2 loss=0.73"
  - sleep 2
  - echo "[NOVA-MLOPS] job=__JOB_NAME__ run_id=__RUN_ID__ step=done"
"""
    return (
        tpl.replace("__JOB_NAME__", job_name)
           .replace("__RUN_ID__", run_id)
    )


def nlp_inference_cloud_init(
    job_name: str,
    run_id: str,
    swift_container: str,
    swift_results_object: str,
    swift_manifest_object: str,
    swift_log_object: str,
    image: str = "",
    flavor: str = "",
    network: str = "",
) -> str:
    tpl = """#cloud-config
package_update: true
packages:
  - util-linux
  - python3-venv
  - python3-full

output:
  all: '| tee -a /dev/console /var/log/cloud-init-output.log'

write_files:
  - path: /var/lib/cloud/scripts/per-once/99-nova-mlops
    permissions: "0755"
    owner: root:root
    content: |
      #!/usr/bin/env bash
      set -euxo pipefail
      echo "[NOVA-MLOPS] per-once start $(date -Is) job=__JOB_NAME__ run_id=__RUN_ID__" | tee /dev/console
      /usr/local/bin/nova-mlops.sh

  - path: /opt/mlops/run_sentiment.py
    permissions: "0644"
    owner: root:root
    content: |
      import json
      import os
      from datetime import datetime, timezone
      from vaderSentiment.vaderSentiment import SentimentIntensityAnalyzer

      job = os.environ.get("NOVA_MLOPS_JOB", "__JOB_NAME__")
      run_id = os.environ.get("NOVA_MLOPS_RUN_ID", "__RUN_ID__")
      input_path = "/tmp/input.txt"

      if os.path.exists(input_path):
          with open(input_path, "r", encoding="utf-8") as f:
              texts = [ln.strip() for ln in f if ln.strip()]
      else:
          texts = [
              "OpenStack executed this workload successfully.",
              "The networking setup was painful but now it's solid.",
              "I would not recommend debugging NAT at midnight."
          ]

      a = SentimentIntensityAnalyzer()
      out = []
      for t in texts:
          s = a.polarity_scores(t)
          out.append({"text": t, **s})
          print(f"[NOVA-MLOPS] job={job} run_id={run_id} compound={s['compound']:+.3f} text={t!r}", flush=True)

      result = {"job": job, "run_id": run_id, "results": out}
      with open("/tmp/result.json", "w", encoding="utf-8") as f:
          json.dump(result, f)

      print("[NOVA-MLOPS] wrote /tmp/result.json", flush=True)

  - path: /opt/mlops/write_manifest.py
    permissions: "0644"
    owner: root:root
    content: |
      import json, os
      from datetime import datetime, timezone

      manifest = {
        "job": os.environ.get("NOVA_MLOPS_JOB"),
        "run_id": os.environ.get("NOVA_MLOPS_RUN_ID"),
        "timestamp_utc": datetime.now(timezone.utc).replace(microsecond=0).isoformat().replace("+00:00","Z"),
        "image": os.environ.get("NOVA_MLOPS_IMAGE"),
        "flavor": os.environ.get("NOVA_MLOPS_FLAVOR"),
        "network": os.environ.get("NOVA_MLOPS_NETWORK"),
        "swift": {
          "container": os.environ.get("NOVA_MLOPS_SWIFT_CONTAINER"),
          "results_object": os.environ.get("NOVA_MLOPS_RESULTS_OBJECT"),
          "manifest_object": os.environ.get("NOVA_MLOPS_MANIFEST_OBJECT"),
          "log_object": os.environ.get("NOVA_MLOPS_LOG_OBJECT"),
        },
        "notes": "Generated by cloud-init on the instance"
      }

      with open("/var/lib/nova-mlops/manifest.json", "w", encoding="utf-8") as f:
        json.dump(manifest, f, indent=2)


  - path: /usr/local/bin/nova-mlops.sh
    permissions: "0755"
    owner: root:root
    content: |
      #!/usr/bin/env bash
      set -euo pipefail

      echo "[NOVA-MLOPS] nova-mlops.sh entered (job=${NOVA_MLOPS_JOB:-?} run_id=${NOVA_MLOPS_RUN_ID:-?})" >/dev/console

      # -----------------------------
      # Basic dirs + logging
      # -----------------------------
      mkdir -p /var/log/mlops /var/lib/nova-mlops
      LOG=/var/log/mlops/job.log
      # mirror stdout+stderr to both file and console
      exec > >(tee -a "$LOG" /dev/console) 2>&1

      # -----------------------------
      # Run identity + object layout
      # -----------------------------
      export NOVA_MLOPS_JOB="__JOB_NAME__"
      export NOVA_MLOPS_RUN_ID="__RUN_ID__"
      export NOVA_MLOPS_SWIFT_CONTAINER="__SWIFT_CONTAINER__"
      export NOVA_MLOPS_RESULTS_OBJECT="__SWIFT_RESULTS_OBJECT__"
      export NOVA_MLOPS_MANIFEST_OBJECT="__SWIFT_MANIFEST_OBJECT__"
      export NOVA_MLOPS_LOG_OBJECT="__SWIFT_LOG_OBJECT__"

      export NOVA_MLOPS_IMAGE="__IMAGE__"
      export NOVA_MLOPS_FLAVOR="__FLAVOR__"
      export NOVA_MLOPS_NETWORK="__NETWORK__"

      echo "[NOVA-MLOPS] job=$NOVA_MLOPS_JOB run_id=$NOVA_MLOPS_RUN_ID starting"

      # -----------------------------
      # Setup python env
      # -----------------------------
      apt-get update -y
      python3 -m venv /opt/mlops-venv
      /opt/mlops-venv/bin/pip install --upgrade pip
      /opt/mlops-venv/bin/pip install vaderSentiment python-openstackclient

      # -----------------------------
      # Swift auth via App Credential
      # -----------------------------
      export OS_AUTH_TYPE="v3applicationcredential"
      export OS_AUTH_URL="http://192.168.122.109/identity"
      export OS_REGION_NAME="RegionOne"
      export OS_INTERFACE="public"
      export OS_IDENTITY_API_VERSION="3"
      export OS_APPLICATION_CREDENTIAL_ID="dab821281aac43439313db09d055005f"
      export OS_APPLICATION_CREDENTIAL_SECRET="rgZ-WTKyBNSKjdwhuUij2vxfjQce4Sr8vjm0IUffuUlIWvr21D7bL-8FaZDg1HK13TtJCJ32QFvm0_5LttsLPg"

      echo "[NOVA-MLOPS] swift container list:"
      /opt/mlops-venv/bin/openstack container list || true

      # Optional: download input.txt
      INPUT=/tmp/input.txt
      if /opt/mlops-venv/bin/openstack object show "$NOVA_MLOPS_SWIFT_CONTAINER" input.txt >/dev/null 2>&1; then
        /opt/mlops-venv/bin/openstack object save "$NOVA_MLOPS_SWIFT_CONTAINER" input.txt --file "$INPUT"
        echo "[NOVA-MLOPS] downloaded swift://$NOVA_MLOPS_SWIFT_CONTAINER/input.txt -> $INPUT"
      else
        echo "[NOVA-MLOPS] no swift input.txt found; using built-in texts"
      fi

      # -----------------------------
      # (Optional) Cinder mount logic
      # -----------------------------
      DEV="/dev/vdb"
      MNT="/mnt/results"
      if [ -b "$DEV" ]; then
        mkdir -p "$MNT"
        if ! blkid "$DEV" >/dev/null 2>&1; then
          mkfs.ext4 -F "$DEV"
        fi
        mount "$DEV" "$MNT"
        echo "[NOVA-MLOPS] mounted $DEV at $MNT"
      else
        echo "[NOVA-MLOPS] no cinder volume detected at $DEV; using /tmp"
        MNT="/tmp"
      fi

      # -----------------------------
      # Run sentiment + write result
      # -----------------------------
      /opt/mlops-venv/bin/python /opt/mlops/run_sentiment.py
      cp -f /tmp/result.json /var/lib/nova-mlops/results.json

      if [ "$MNT" != "/tmp" ]; then
        cp -f /tmp/result.json "$MNT/result.json"
        echo "[NOVA-MLOPS] copied result to $MNT/result.json"
      else
        echo "[NOVA-MLOPS] MNT=/tmp, skipping copy"
      fi

      /opt/mlops-venv/bin/python /opt/mlops/write_manifest.py


      sync
      echo "[NOVA-MLOPS] done; uploading to swift"

      /opt/mlops-venv/bin/openstack object create "$NOVA_MLOPS_SWIFT_CONTAINER" /var/lib/nova-mlops/results.json --name "$NOVA_MLOPS_RESULTS_OBJECT"
      /opt/mlops-venv/bin/openstack object create "$NOVA_MLOPS_SWIFT_CONTAINER" /var/lib/nova-mlops/manifest.json --name "$NOVA_MLOPS_MANIFEST_OBJECT"
      /opt/mlops-venv/bin/openstack object create "$NOVA_MLOPS_SWIFT_CONTAINER" "$LOG" --name "$NOVA_MLOPS_LOG_OBJECT"

      echo "===MLOPS_RESULT==="; cat /tmp/result.json
      poweroff


runcmd:
  - [ bash, -lc, 'echo "[NOVA-MLOPS] RUNCMD HIT $(date -Is)" | tee /dev/console' ]
  - [ bash, -lc, 'ls -l /var/lib/cloud/scripts/per-once | tee /dev/console' ]
  - [ bash, -lc, 'chmod +x /var/lib/cloud/scripts/per-once/99-nova-mlops || true' ]
  - [ bash, -lc, '/var/lib/cloud/scripts/per-once/99-nova-mlops' ]


final_message: |
  [NOVA-MLOPS] cloud-init finished. per-once script should have started the job.
"""
    return (
        tpl.replace("__JOB_NAME__", job_name)
           .replace("__RUN_ID__", run_id)
           .replace("__SWIFT_CONTAINER__", swift_container)
           .replace("__SWIFT_RESULTS_OBJECT__", swift_results_object)
           .replace("__SWIFT_MANIFEST_OBJECT__", swift_manifest_object)
           .replace("__SWIFT_LOG_OBJECT__", swift_log_object)
           .replace("__IMAGE__", image)
           .replace("__FLAVOR__", flavor)
           .replace("__NETWORK__", network)
    )

